sudo: false
language: haskell
cache: apt

addons:
  apt_packages:
      - libblas-dev
      - libatlas-dev
      - liblapack-dev

ghc:
    - 7.8

install:
    - cabal update
    - cabal install --only-dependencies

script:
    - cabal configure && cabal build
